export default {
    dominos: require('../../img/deals/dominos.png'),
    walkabout: require('../../img/deals/walkabout.jpg'),
    better: require('../../img/deals/better.png'),
    smack: require('../../img/deals/smack.jpg'),
    quidz: require('../../img/deals/quidz.jpg'),
    steinbeck: require('../../img/deals/steinbeck.jpg'),
    libertine: require('../../img/deals/libertine.jpg'),
    iSawItFirst: require('../../img/deals/i-saw-it-first.png'),
    oldHavanna: require('../../img/deals/old-havana.jpg'),
    sbaArtwork: require('../../img/deals/sba-artwork.jpg'),
    revolution: require('../../img/deals/revolution.jpg'),
    judyVintage: require('../../img/deals/judy-vintage.jpg'),
    goodLife: require('../../img/deals/good-life.jpg'),
    valeWarehouse: require('../../img/deals/vale-warehouse.png'),
    robotMonkey: require('../../img/deals/robot-monkey.jpg'),
    libertine: require('../../img/deals/libertine.jpg'),
    ciliegino: require('../../img/deals/ciliegino.jpg'),
    overheardLive: require('../../img/deals/overheard-live.jpg'),
    footasylum: require('../../img/deals/footasylum.jpg'),
    skinnyDip: require('../../img/deals/skinny-dip.png'),
    dazed: require('../../img/deals/dazed.png'),
    dazedDisco: require('../../img/deals/dazed-disco.jpg'),
    tiger: require('../../img/deals/tiger.png'),
    capitalCabs: require('../../img/deals/capital-cabs.png'),
    discoWonderland: require('../../img/deals/disco-wonderland.jpg'),
    weLoveItaly: require('../../img/deals/we-love-italy.jpg'),
    depot: require('../../img/deals/depot.jpg'),
    mamas: require('../../img/deals/mamas.jpg'),
    belleToujours: require('../../img/deals/belle-toujours.png'),
    lazarou: require('../../img/deals/lazarou.jpg'),
    foreverlandArtwork: require('../../img/deals/foreverland-artwork.png'),
    shangriLa: require('../../img/deals/shangri-la.jpg'),
    buzzpark: require('../../img/deals/buzzpark.png'),
    piatto: require('../../img/deals/piatto.png'),
    mode: require('../../img/deals/mode.jpg'),
    bwydiful: require('../../img/deals/bwydiful.jpg'),
    slunks: require('../../img/deals/slunks.jpg'),
    breakout: require('../../img/deals/breakout.png'),
    resooma: require('../../img/deals/resooma.jpg'),
    caseUp: require('../../img/deals/case-up.png'),
    fotd: require('../../img/deals/fotd.png'),
    hollyAdine: require('../../img/deals/holly-adine.jpg'),
    moomoos: require('../../img/deals/moomoos.png'),
    pitch: require('../../img/deals/pitch.jpg'),
    masalaBag: require('../../img/deals/masala-bag.png'),
    made: require('../../img/deals/made.jpg'),
    vapeNation: require('../../img/deals/vape-nation.jpg'),
    greaseMonkeys: require('../../img/deals/grease-monkeys.jpg'),
    dcjValeting: require('../../img/deals/cj-valeting.jpg'),
    juniperPlace: require('../../img/deals/juniper-place.jpg'),
    // dominos: require('../../img/deals/dominos.png'),
    // dominos: require('../../img/deals/dominos.png'),
    // dominos: require('../../img/deals/dominos.png'),
    // dominos: require('../../img/deals/dominos.png'),
    // dominos: require('../../img/deals/dominos.png'),
    // dominos: require('../../img/deals/dominos.png'),
    // dominos: require('../../img/deals/dominos.png'),
    // dominos: require('../../img/deals/dominos.png'),
    // dominos: require('../../img/deals/dominos.png'),
    // dominos: require('../../img/deals/dominos.png'),
    // dominos: require('../../img/deals/dominos.png'),
    // dominos: require('../../img/deals/dominos.png'),
    // dominos: require('../../img/deals/dominos.png'),
    // dominos: require('../../img/deals/dominos.png'),
    // dominos: require('../../img/deals/dominos.png'),
    // dominos: require('../../img/deals/dominos.png'),
    // dominos: require('../../img/deals/dominos.png'),
    // dominos: require('../../img/deals/dominos.png'),
    // dominos: require('../../img/deals/dominos.png'),
    // dominos: require('../../img/deals/dominos.png'),
    // dominos: require('../../img/deals/dominos.png'),
  };